spring:
  application:
    name: projectlinker-server
  profiles:
    active: jwt, mail
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: projectlinker
    password: projectlinker
    url: jdbc:mysql://localhost:3306/projectlinker?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8082
logging:
  level:
    org:
      springframework:
        security: DEBUG